# Generated by Django 2.2.12 on 2020-06-04 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_parceiro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parceiro',
            new_name='Parceiros',
        ),
    ]
