# Generated by Django 2.2.12 on 2020-06-04 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200604_1817'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parceiros',
            new_name='Parceiro',
        ),
    ]
