# Generated by Django 2.2.12 on 2020-06-04 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200604_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parceiro',
            name='cpf',
        ),
    ]
