# Generated by Django 2.2.12 on 2020-06-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_parceiro_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parceiro',
            old_name='Nome',
            new_name='parceiro',
        ),
    ]
