# Generated by Django 2.2.12 on 2020-06-06 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200605_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='parceiro',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='blog.Parceiro'),
            preserve_default=False,
        ),
    ]
