# Generated by Django 2.2.12 on 2020-06-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_parceiro_parceiro_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='importado',
            field=models.CharField(max_length=30, verbose_name='Origem'),
        ),
    ]
