# Generated by Django 2.2.12 on 2020-06-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200607_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo_produto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
