# Generated by Django 2.2.12 on 2020-06-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200608_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='importado',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Origem'),
        ),
    ]
