# Generated by Django 2.2.12 on 2020-06-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200608_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='importado',
            field=models.BooleanField(blank=True, max_length=30, null=True, verbose_name='Origem'),
        ),
    ]
