# Generated by Django 2.2.12 on 2020-06-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200608_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='importado',
            field=models.BooleanField(default=False),
        ),
    ]
