# Generated by Django 2.2.12 on 2020-06-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200608_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo_produto',
            field=models.CharField(blank=True, choices=[('Produto Acabado', 'Produto Acabado'), ('Matéria Prima', 'Matéria Prima')], max_length=30),
        ),
    ]
